# ===========================================================================
# AIKONIC — CS 322 | LBW Risk Prediction
# File: src/05_threshold_validation.py
#
# Purpose : Select and save the optimal classification threshold using
#           exclusively out-of-fold (OOF) probabilities from 04.
#           Saves threshold.pkl and features.json as SEPARATE artifacts.
#
# Input  : artifacts/oof_probabilities.pkl
# Output : artifacts/threshold.pkl
#          artifacts/features.json
#          outputs/threshold_analysis.png
#          outputs/threshold_selection_table.csv
#
# CRITICAL DESIGN RULE:
#   The threshold is selected on OOF probabilities (training-derived).
#   It is NEVER selected using test or unseen data.
#   Using test/unseen probabilities for threshold selection is data leakage —
#   it optimizes the threshold on the very data used to evaluate it.
#
# WHY threshold.pkl IS SEPARATE FROM model.pkl:
#   1. The threshold can be recalibrated (e.g., for a new health district
#      with different risk tolerance) without retraining the model.
#   2. The prototype loads model.pkl and threshold.pkl independently —
#      this makes the system modular and auditable.
#   3. A panel can inspect the threshold decision independently from
#      the model's internal parameters.
#
# Connects to: 06_evaluation.py, prototype/predictor.py
# ===========================================================================

import os, sys, json, warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import joblib

warnings.filterwarnings('ignore')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from config import (
    OOF_PATH, ARTIFACTS_DIR, OUTPUTS_DIR, THRESHOLD_PATH,
    FEATURES_PATH, FEATURE_COLS, MIN_RECALL_FLOOR
)

from sklearn.metrics import (
    roc_auc_score, precision_recall_curve, f1_score,
    precision_score, recall_score
)
# ─── Threshold Selection ─────────────────────────────────────────────────────

def select_threshold(oof_proba: np.ndarray, y_train: pd.Series) -> float:
    """
    Recall-prioritized threshold selection on OOF probabilities.

    CRITERION:
      Find the HIGHEST threshold such that Recall on OOF data is still
      >= MIN_RECALL_FLOOR (default: 0.50).

    WHY HIGHEST THRESHOLD (most conservative meeting the recall floor):
      We want to minimize false positives (unnecessary RHU referrals) while
      guaranteeing the recall floor. The highest valid threshold achieves
      this balance — it sends the fewest false positives while still catching
      at least MIN_RECALL_FLOOR of true LBW cases.

    WHY MIN_RECALL = 0.50:
      A system that misses more than half of LBW mothers provides less value
      than a policy of monitoring all mothers equally. 50% is the minimum
      clinical meaningfulness threshold for this triage context.

    WHY ON OOF PROBABILITIES (not test):
      OOF probabilities are generated by cross-validation on training data.
      They represent the expected probability distribution on new data from
      the same source, without contaminating the evaluation sets.

    FALLBACK:
      If no threshold achieves Recall >= MIN_RECALL_FLOOR, maximize F1.
      This indicates the model is too weak and should be investigated,
      but the pipeline continues with a degraded threshold.

    Returns float: the selected threshold.
    """
    prec_c, rec_c, thr_c = precision_recall_curve(y_train, oof_proba)

    # Build candidate table
    rows = []
    for prec, rec, thr in zip(prec_c[:-1], rec_c[:-1], thr_c):
        f1 = (2 * prec * rec / (prec + rec)) if (prec + rec) > 0 else 0.0
        rows.append({'threshold': thr, 'precision': prec, 'recall': rec, 'f1': f1})
    cand_df = pd.DataFrame(rows)

    valid = cand_df[cand_df['recall'] >= MIN_RECALL_FLOOR]

    if len(valid) > 0:
        # Highest threshold still meeting recall floor
        best    = valid.loc[valid['threshold'].idxmax()]
        method  = f"Recall-prioritized (recall ≥ {MIN_RECALL_FLOOR})"
        warning = False
    else:
        # Fallback: F1 maximization
        best    = cand_df.loc[cand_df['f1'].idxmax()]
        method  = f"F1-fallback (no threshold achieves recall ≥ {MIN_RECALL_FLOOR})"
        warning = True
        print(f"\n  ⚠  WARNING: No threshold achieves Recall >= {MIN_RECALL_FLOOR} on OOF data.")
        print(f"  ⚠  Model may be too weak for reliable screening.")
        print(f"  ⚠  Using F1-maximizing threshold as fallback.")

    threshold = float(best['threshold'])
    t_prec    = float(best['precision'])
    t_rec     = float(best['recall'])
    t_f1      = float(best['f1'])

    print(f"\n  [THRESHOLD] Method     : {method}")
    print(f"  [THRESHOLD] Value      : {threshold:.4f}")
    print(f"  [THRESHOLD] OOF Recall : {t_rec:.4f}")
    print(f"  [THRESHOLD] OOF Prec   : {t_prec:.4f}")
    print(f"  [THRESHOLD] OOF F1     : {t_f1:.4f}")

    return threshold, cand_df
# ─── Threshold Sensitivity Table ─────────────────────────────────────────────

def build_sensitivity_table(oof_proba: np.ndarray,
                             y_train: pd.Series,
                             selected: float) -> pd.DataFrame:
    """
    Show model performance across a range of thresholds.
    This table belongs in the thesis Results section as evidence for
    the threshold selection rationale.
    """
    rows = []
    for t in np.arange(0.10, 0.70, 0.05):
        pred = (oof_proba >= t).astype(int)
        prec = precision_score(y_train, pred, zero_division=0)
        rec  = recall_score(y_train, pred, zero_division=0)
        f1   = f1_score(y_train, pred, zero_division=0)
        flagged = pred.sum()
        rows.append({
            'Threshold': round(t, 2),
            'Precision': round(prec, 4),
            'Recall':    round(rec, 4),
            'F1':        round(f1, 4),
            'Flagged_N': int(flagged),
            'Selected':  '← SELECTED' if abs(t - selected) < 0.026 else '',
        })
    return pd.DataFrame(rows)
# ─── Visualization ──────────────────────────────────────────────────────────

def plot_threshold_analysis(oof_proba: np.ndarray, y_train: pd.Series,
                             cand_df: pd.DataFrame, threshold: float) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle(
        f'Threshold Selection — OOF Probabilities | Selected: t={threshold:.4f}',
        fontsize=13, fontweight='bold'
    )

    # Left: Precision-Recall curve
    prec_c, rec_c, thr_c = precision_recall_curve(y_train, oof_proba)
    ax = axes[0]
    ax.plot(rec_c, prec_c, '#4472C4', lw=2)
    ax.axvline(MIN_RECALL_FLOOR, color='gray', linestyle=':', alpha=0.7,
               label=f'Recall floor = {MIN_RECALL_FLOOR}')
    # Mark selected threshold on curve
    sel_row = cand_df.iloc[(cand_df['threshold'] - threshold).abs().argsort()[:1]]
    if len(sel_row) > 0:
        ax.scatter(sel_row['recall'].values[0], sel_row['precision'].values[0],
                   color='red', s=150, zorder=5, label=f'Selected t={threshold:.4f}')
    ax.set_xlabel('Recall')
    ax.set_ylabel('Precision')
    ax.set_title('Precision-Recall Curve (OOF)', fontweight='bold')
    ax.legend(fontsize=9)
    ax.grid(linestyle='--', alpha=0.4)

    # Right: Recall and F1 vs Threshold
    ax2 = axes[1]
    ax2.plot(cand_df['threshold'], cand_df['recall'], '#4472C4', lw=2,
             linestyle='--', label='Recall')
    ax2.plot(cand_df['threshold'], cand_df['f1'],     '#ED7D31', lw=2,
             label='F1')
    ax2.axvline(threshold, color='red', linestyle='--', lw=1.5,
                label=f'Selected t={threshold:.4f}')
    ax2.axhline(MIN_RECALL_FLOOR, color='gray', linestyle=':', alpha=0.7,
                label=f'Recall floor = {MIN_RECALL_FLOOR}')
    ax2.set_xlabel('Threshold')
    ax2.set_ylabel('Score')
    ax2.set_title('Recall & F1 vs Threshold (OOF)', fontweight='bold')
    ax2.legend(fontsize=9)
    ax2.grid(linestyle='--', alpha=0.4)

    plt.tight_layout()
    os.makedirs(OUTPUTS_DIR, exist_ok=True)
    plt.savefig(os.path.join(OUTPUTS_DIR, 'threshold_analysis.png'),
                dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\n  [SAVED] threshold_analysis.png")
    # ─── Main ────────────────────────────────────────────────────────────────────

def run_threshold_validation() -> float:
    print("=" * 65)
    print("STAGE 5: THRESHOLD SELECTION AND VALIDATION")
    print("=" * 65)
    print("\n  ⚠  Threshold computed EXCLUSIVELY on OOF probabilities.")
    print("  ⚠  Test and unseen data are NOT used here.")

    pkg       = joblib.load(OOF_PATH)
    oof_proba = pkg['oof_proba']
    y_train   = pkg['y_train']

    oof_auc = roc_auc_score(y_train, oof_proba)
    print(f"\n  [OOF] OOF ROC-AUC: {oof_auc:.4f}")
    print(f"  [OOF] OOF LBW rate: {y_train.mean()*100:.1f}% ({y_train.sum()} cases)")

    threshold, cand_df = select_threshold(oof_proba, y_train)

    sens_table = build_sensitivity_table(oof_proba, y_train, threshold)
    print(f"\n  [SENSITIVITY] Threshold Sensitivity Table (OOF):")
    print(sens_table.to_string(index=False))

    plot_threshold_analysis(oof_proba, y_train, cand_df, threshold)

    os.makedirs(ARTIFACTS_DIR, exist_ok=True)

    # Save threshold.pkl — SEPARATE from model.pkl (by design)
    joblib.dump(threshold, THRESHOLD_PATH)
    print(f"\n  [SAVED] threshold.pkl = {threshold:.4f}")

    # Save features.json — for prototype schema validation
    with open(FEATURES_PATH, 'w') as f:
        json.dump({'features': FEATURE_COLS, 'n_features': len(FEATURE_COLS)}, f, indent=2)
    print(f"  [SAVED] features.json ({len(FEATURE_COLS)} features)")

    # Save sensitivity table
    sens_table.to_csv(
        os.path.join(OUTPUTS_DIR, 'threshold_selection_table.csv'), index=False
    )
    print(f"  [SAVED] threshold_selection_table.csv")

    print(f"\n  [SUMMARY] Selected threshold: {threshold:.4f}")
    print(f"  [SUMMARY] This threshold will be applied IDENTICALLY to")
    print(f"            CV (OOF), Test, and Unseen sets in 06_evaluation.py.")
    return threshold

if __name__ == "__main__":
    run_threshold_validation()