# ===========================================================================
# AIKONIC — CS 322 | LBW Risk Prediction
# File: src/05_threshold_validation.py
#
# Purpose : Select and save the optimal classification threshold using
#           exclusively out-of-fold (OOF) probabilities from 04.
#           Saves threshold.pkl and features.json as SEPARATE artifacts.
#
# Input  : artifacts/oof_probabilities.pkl
# Output : artifacts/threshold.pkl
#          artifacts/features.json
#          outputs/threshold_analysis.png
#          outputs/threshold_selection_table.csv
#
# CRITICAL DESIGN RULE:
#   The threshold is selected on OOF probabilities (training-derived).
#   It is NEVER selected using test or unseen data.
#   Using test/unseen probabilities for threshold selection is data leakage —
#   it optimizes the threshold on the very data used to evaluate it.
#
# WHY threshold.pkl IS SEPARATE FROM model.pkl:
#   1. The threshold can be recalibrated (e.g., for a new health district
#      with different risk tolerance) without retraining the model.
#   2. The prototype loads model.pkl and threshold.pkl independently —
#      this makes the system modular and auditable.
#   3. A panel can inspect the threshold decision independently from
#      the model's internal parameters.
#
# Connects to: 06_evaluation.py, prototype/predictor.py
# ===========================================================================

import os, sys, json, warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import joblib

warnings.filterwarnings('ignore')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from config import (
    OOF_PATH, ARTIFACTS_DIR, OUTPUTS_DIR, THRESHOLD_PATH,
    FEATURES_PATH, FEATURE_COLS, MIN_RECALL_FLOOR
)

from sklearn.metrics import (
    roc_auc_score, precision_recall_curve, f1_score,
    precision_score, recall_score
)
# ─── Threshold Selection ─────────────────────────────────────────────────────

def select_threshold(oof_proba: np.ndarray, y_train: pd.Series) -> float:
    """
    Recall-prioritized threshold selection on OOF probabilities.

    CRITERION:
      Find the HIGHEST threshold such that Recall on OOF data is still
      >= MIN_RECALL_FLOOR (default: 0.50).

    WHY HIGHEST THRESHOLD (most conservative meeting the recall floor):
      We want to minimize false positives (unnecessary RHU referrals) while
      guaranteeing the recall floor. The highest valid threshold achieves
      this balance — it sends the fewest false positives while still catching
      at least MIN_RECALL_FLOOR of true LBW cases.

    WHY MIN_RECALL = 0.50:
      A system that misses more than half of LBW mothers provides less value
      than a policy of monitoring all mothers equally. 50% is the minimum
      clinical meaningfulness threshold for this triage context.

    WHY ON OOF PROBABILITIES (not test):
      OOF probabilities are generated by cross-validation on training data.
      They represent the expected probability distribution on new data from
      the same source, without contaminating the evaluation sets.

    FALLBACK:
      If no threshold achieves Recall >= MIN_RECALL_FLOOR, maximize F1.
      This indicates the model is too weak and should be investigated,
      but the pipeline continues with a degraded threshold.

    Returns float: the selected threshold.
    """
    prec_c, rec_c, thr_c = precision_recall_curve(y_train, oof_proba)

    # Build candidate table
    rows = []
    for prec, rec, thr in zip(prec_c[:-1], rec_c[:-1], thr_c):
        f1 = (2 * prec * rec / (prec + rec)) if (prec + rec) > 0 else 0.0
        rows.append({'threshold': thr, 'precision': prec, 'recall': rec, 'f1': f1})
    cand_df = pd.DataFrame(rows)

    valid = cand_df[cand_df['recall'] >= MIN_RECALL_FLOOR]

    if len(valid) > 0:
        # Highest threshold still meeting recall floor
        best    = valid.loc[valid['threshold'].idxmax()]
        method  = f"Recall-prioritized (recall ≥ {MIN_RECALL_FLOOR})"
        warning = False
    else:
        # Fallback: F1 maximization
        best    = cand_df.loc[cand_df['f1'].idxmax()]
        method  = f"F1-fallback (no threshold achieves recall ≥ {MIN_RECALL_FLOOR})"
        warning = True
        print(f"\n  ⚠  WARNING: No threshold achieves Recall >= {MIN_RECALL_FLOOR} on OOF data.")
        print(f"  ⚠  Model may be too weak for reliable screening.")
        print(f"  ⚠  Using F1-maximizing threshold as fallback.")

    threshold = float(best['threshold'])
    t_prec    = float(best['precision'])
    t_rec     = float(best['recall'])
    t_f1      = float(best['f1'])

    print(f"\n  [THRESHOLD] Method     : {method}")
    print(f"  [THRESHOLD] Value      : {threshold:.4f}")
    print(f"  [THRESHOLD] OOF Recall : {t_rec:.4f}")
    print(f"  [THRESHOLD] OOF Prec   : {t_prec:.4f}")
    print(f"  [THRESHOLD] OOF F1     : {t_f1:.4f}")

    return threshold, cand_df